config/routes.rb
Rails.application.routes.draw do

  root to: "desktops#show"

#Navbar

  resource :navbar_system_status

#Users

  get 'sign_in', to: redirect('/users/sign_in')

  devise_for :users, skip: :registrations, :controllers => { :sessions => "user_sessions" }
  resource :user, only: :show
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # resource :user_password

#Desktop

  resource :desktop
  resource :desktop_applications

#Control panel

  resource :control_panel do
    get :services
  end
  resource :control_panel_applications
  resource :control_panel_services
  resource :services_registry
  resource :control_panel_applications_states
  resource :control_panel_services_states

#System

  resource :system_monitor_charts do
    get :system_cpu_usage
    get :system_cpu_usage_averages
    get :total_system_memory_usage
    get :total_container_memory_usage
    get :container_memory_usage
    get :total_applications_memory_usage
    get :applications_memory_usage
    get :total_services_memory_usage
    get :services_memory_usage
    get :disk_usage
    get :network_usage
  end

  resource :system_monitor_charts

  resource :system do
    get :monitor, :status, :info, :logs, :base_system, :updater, :restart
  end
  resource :system_restart do
    get :progress
  end
  resource :system_engines_update do
    get :progress
  end
  resource :system_base_update do
    get :progress
  end
  resource :system_restart_mgmt do
    get :progress
  end
  resource :system_restart_registry do
    get :progress
  end

  resource :system_security
  resource :system_security_certificate do
    get :download
  end
  resource :system_security_key do
    get :new_download
    post :download
  end
  resource :system_bug_reports

#Domains

  resource :domains_manager
  resource :domain
  resource :domain_certificate
  resource :domain_default_name
  resource :domain_default_site

#Display settings

  resource :display_settings

#Libraries

  resources :libraries
  resource :library_software do
    get :tags_list
  end
  resource :library_settings

#Applications

  resource :application_network_properties
  resource :application_resources_properties
  resource :application_variables_properties
  resource :application_display_properties
  resource :application_services_properties
  resource :application_service do
    get :action
  end
  resource :application_service_connector_type
  resource :application_service_connector_configuration
  resource :application_action do
    get :perform
  end
  resource :application_report do
    get :installation_report
  end
  resource :application_about
  resource :orphaned_application_service
  resource :application_service_connection_subservice_connection
  resource :application_service_connection_subservice_connector_configuration
  resource :application_service_data_export
  resource :application_service_data_import
  resource :application_uninstall
  resource :applications do
    get(
      :start_container, :stop_container, :pause_container, :unpause_container, :restart_container,
      :create_container, :destroy_container, :recreate_container,
      :reinstall, :open_first_run, :reload)
  end

#Services

  resource :service_report
  resource :service_configuration
  resource :service_action do
    get :perform
  end
  resource :services do
    get(
      :pause_container, :unpause_container, :start_container, :stop_container,
      :restart_container, :recreate_container, :create_container, :reload) # :show,
  end

#Installer

  resource :installer
  resource :application_installation do
    get(:preparing_installation, :preparing_installation_progress, :installing,
     :progress, :cancel)
  end
  resource :install_from_blueprint
  resource :install_from_repository_url
  resource :install_from_docker_hub
  resource :install_from_docker_hub_configuration

#First run

  resource :first_run do
    get :cancel
  end

#Help

  resource :help

end

app/models/application_service.rb
class ApplicationService < ActiveRecord::Base

  attr_accessor :connection_params,
                :service_action,
                :engines_api_error

  belongs_to :application
  has_many :variables, as: :variable_consumer, dependent: :destroy
  # has_many :application_subservices, dependent: :destroy

  accepts_nested_attributes_for :variables

  def existing_connection
    @existing_connection ||= ApplicationServiceConnection.new(self)
  end

  def edit_connection_params
    {
      application_name: application.container_name,
      application_service: {
        connection_params: connection_params
      }
    }
  end

  def new_record?
    false
  end

  def update
    valid? && existing_connection.update
  end

  def destroy
    existing_connection.destroy
  end

  def perform_action
    existing_connection.perform_action
  end

end

app/controllers/application_services_controller.rb
class ApplicationServicesController < ApplicationController

  before_action :set_application_service

  def edit
    @application_service.existing_connection.build_edit
  end

  def update
    # render text: @application_service.existing_connection.update_params
    if @application_service.update
      redirect_to application_services_properties_path(application_name: @application_service.application.container_name),
        notice: "Successfully updated #{@application_service.application.container_name} #{@application_service.existing_connection.service_detail.title}." +
                  @application_service.engines_api_error.to_s
    else
      render :edit
    end
  end

  def destroy
    # render text: @application_service.existing_connection.connection_params
    if @application_service.destroy
      redirect_to application_services_properties_path(application_name: @application_service.application.container_name),
        notice: "Successfully removed #{@application_service.existing_connection.service_detail.title} from #{@application_service.application.container_name}."
    else
      redirect_to application_services_properties_path(application_name: @application_service.application.container_name),
        alert: "Unable to remove #{@application_service.existing_connection.service_detail.title} from #{@application_service.application.container_name}." +
                  @application_service.engines_api_error.to_s
    end
  end

  def action
    if @application_service.perform_action
      redirect_to application_services_properties_path(application_name: @application_service.application.container_name),
        notice: "Successfully performed #{@application_service.service_action} action on #{@application_service.existing_connection.service_detail.title}."
    else
      redirect_to application_services_properties_path(application_name: @application_service.application.container_name),
        alert: "Unable to perform #{@application_service.service_action} action on #{@application_service.existing_connection.service_detail.title}. " +
                  @application_service.engines_api_error.to_s
    end
  end

private

  def set_application_service
    @application_service = application.application_services.build(application_service_params)
  end

  def application
    Application.find_by(container_name: application_name)
  end

  def application_name
    params[:application_name]
  end

  def application_service_params
    params.require(:application_service).permit!
  end

end

app/views/application_services/_form_fields.html.erb
<% f.object.connection_params.each do |key,value| %>
<%= hidden_field_tag "application_service[connection_params][#{key}]",value %>
<% end %>
<%= render partial: 'shared/form/errors', locals: {f: f} %>
<%= render partial: 'variables/form_fields', locals: {f: f} %>

app/views/application_services/_new_attached_service_button.html.erb
<% 	available_services = @application.available_services %>

<div class="dropdown pull-right">

	<button class="btn btn-lg btn-default dropdown-toggle" type="button" data-toggle="dropdown">
		<%= content_tag(:i, "", class: "fa fa-plus-circle") + " Add service" %>
		<span class="caret"></span>
	</button>
	<ul class="dropdown-menu" role="menu">

		<% available_services.each do |available_service| %>
		<li>
			<%= link_to(
			available_service[:title],
			new_application_services_path(
			application_name: @application.container_name,
			application_service: {
			# title: available_service[:title],
			# description: available_service[:description],
			type_path: available_service[:type_path],
			publisher_namespace: available_service[:publisher_namespace],
			# variables_attributes: (available_service[:setup_params] || {} ).values
			}
			),
			class: "btn-lg trigger-response-modal")
			%>

		</li>
		<% end %>

	</ul>
</div>

app/views/application_services/edit.html.erb
<div class="col-sm-12">
	<h2><i class='fa fa-arrows-v'></i> Edit <%= @application_service.existing_connection.service_detail.title %> on <%= @application_service.application.container_name %></h2>
  	<%= form_for @application_service, url: application_service_path(application_name: @application_service.application.container_name), method: :patch do |f| %>
		<%= render 'form_fields', f: f %>
	  <%= render partial: 'shared/form/cancel_and_submit_buttons', locals: {f: f, cancel_path: application_services_properties_path(application_name: @application_service.application.container_name)} %>
	<% end %>
</div>
<% #= ap(@application_service.service_detail, index: false, plain: true).html_safe %>