config/routes.rb
Rails.application.routes.draw do

  root to: "desktops#show"

#Navbar

  resource :navbar_system_status

#Users

  get 'sign_in', to: redirect('/users/sign_in')

  devise_for :users, skip: :registrations, :controllers => { :sessions => "user_sessions" }
  resource :user, only: :show
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # resource :user_password

#Desktop

  resource :desktop
  resource :desktop_applications

#Control panel

  resource :control_panel do
    get :services
  end
  resource :control_panel_applications
  resource :control_panel_services
  resource :services_registry
  resource :control_panel_applications_states
  resource :control_panel_services_states

#System

  resource :system_monitor_charts do
    get :system_cpu_usage
    get :system_cpu_usage_averages
    get :total_system_memory_usage
    get :total_container_memory_usage
    get :container_memory_usage
    get :total_applications_memory_usage
    get :applications_memory_usage
    get :total_services_memory_usage
    get :services_memory_usage
    get :disk_usage
    get :network_usage
  end

  resource :system_monitor_charts

  resource :system do
    get :monitor, :status, :info, :logs, :base_system, :updater, :restart
  end
  resource :system_restart do
    get :progress
  end
  resource :system_engines_update do
    get :progress
  end
  resource :system_base_update do
    get :progress
  end
  resource :system_restart_mgmt do
    get :progress
  end
  resource :system_restart_registry do
    get :progress
  end

  resource :system_security
  resource :system_security_certificate do
    get :download
  end
  resource :system_security_key do
    get :new_download
    post :download
  end
  resource :system_bug_reports

#Domains

  resource :domains_manager
  resource :domain
  resource :domain_certificate
  resource :domain_default_name
  resource :domain_default_site

#Display settings

  resource :display_settings

#Libraries

  resources :libraries
  resource :library_software do
    get :tags_list
  end
  resource :library_settings

#Applications

  resource :application_network_properties
  resource :application_resources_properties
  resource :application_variables_properties
  resource :application_display_properties
  resource :application_services_properties
  resource :application_service do
    get :action
  end
  resource :application_service_connector_type
  resource :application_service_connector_configuration
  resource :application_action do
    get :perform
  end
  resource :application_report do
    get :installation_report
  end
  resource :application_about
  resource :orphaned_application_service
  resource :application_service_connection_subservice_connection
  resource :application_service_connection_subservice_connector_configuration
  resource :application_service_data_export
  resource :application_service_data_import
  resource :application_uninstall
  resource :applications do
    get(
      :start_container, :stop_container, :pause_container, :unpause_container, :restart_container,
      :create_container, :destroy_container, :recreate_container,
      :reinstall, :open_first_run, :reload)
  end

#Services

  resource :service_report
  resource :service_configuration
  resource :service_action do
    get :perform
  end
  resource :services do
    get(
      :pause_container, :unpause_container, :start_container, :stop_container,
      :restart_container, :recreate_container, :create_container, :reload) # :show,
  end

#Installer

  resource :installer
  resource :application_installation do
    get(:preparing_installation, :preparing_installation_progress, :installing,
     :progress, :cancel)
  end
  resource :install_from_blueprint
  resource :install_from_repository_url
  resource :install_from_docker_hub
  resource :install_from_docker_hub_configuration

#First run

  resource :first_run do
    get :cancel
  end

#Help

  resource :help

end

app/models/install_from_docker_hub.rb
class InstallFromDockerHub < ActiveRecord::Base

  include Engines::Api

  belongs_to :application
  accepts_nested_attributes_for :application
  
  attr_accessor(
    :docker_image,
    :type,
    :run_as_user,
    :run_command,
    :new_application_service_publisher_namespace,
    :new_application_service_type_path,
    :new_environment_variable,
    :new_eport,
    :scroll_form_to )

  validate :docker_image_validation

  def self.build_new
    new.tap do |new_install|
      new_install.type = "Software"
      new_install.build_application
    end
  end

  def self.build_configuration(install_from_docker_hub_params)
    new(install_from_docker_hub_params).tap do |result|
      result.type = 'Software'
      result.application.build_application_resources_properties
      result.application.build_application_network_properties(http_protocol: :http_https)
      result.application.application_service_connectors.each(&:load_application_service_connector_configuration_variables)
    end
  end
  
  def new_record?
    true
  end

  def ready_to_install?
    valid?
  end

  def ready_to_configure?
    !load_new_form_elements && valid?
  end

  def load_new_form_elements
    if new_application_service_publisher_namespace.present? && new_application_service_type_path.present?
      build_application unless application
      application.application_service_connectors.
        build(publisher_namespace: new_application_service_publisher_namespace,
              type_path: new_application_service_type_path,
              application_service_connector_type_attributes: {create_type: :new})
      self.new_application_service_type_path = nil
      self.new_application_service_publisher_namespace = nil
      self.scroll_form_to = :application_service_fields
      true
    elsif new_environment_variable.present?
      build_application unless application
      application.variables.build
      self.scroll_form_to = :environment_variable_fields
      self.new_environment_variable = nil
      true
    elsif new_eport.present?
      build_application unless application
      application.eports.build(protocol: 'TCP')
      self.scroll_form_to = :eport_fields
      self.new_eport = nil
      true
    else
      self.scroll_form_to = nil
      false
    end
  end

  def new_configuration_params
    {
      install_from_docker_hub: {
        docker_image: docker_image,
        application_attributes: {
          container_name: application.container_name,
          application_service_connectors_attributes: new_configuration_application_application_service_connectors_params,
          variables_attributes: new_configuration_application_variables_params,
          eports_attributes: new_configuration_application_eports_params
        }
      }
    }
  end

  def new_configuration_application_application_service_connectors_params
    result = {}
    application.application_service_connectors.map.with_index do |application_service_connector, i|
      result[i.to_s] = {
        type_path: application_service_connector.type_path,
        publisher_namespace: application_service_connector.publisher_namespace,
        parent_engine_name: application.container_name,
        application_service_connector_configuration_attributes: {
          create_type: application_service_connector.application_service_connector_type.create_type,
          existing_service: application_service_connector.application_service_connector_type.existing_service_params_json
        }
      }
    end
    result
  end
  
  def new_configuration_application_variables_params
    result = {}
    application.variables.map.with_index do |variable, i|
      result[i.to_s] = { name: variable.name, value: variable.value }
    end
    result
  end
  
  def new_configuration_application_eports_params
    result = {}
    application.eports.map.with_index do |eport, i|
      result[i.to_s] = { name: eport.name, internal_port: eport.internal_port, external_port: eport.external_port, protocol: eport.protocol.to_s.downcase.underscore }
    end
    result
  end
  
  def installation_params
    {
      engine_name: application.container_name,
      memory: application.application_resources_properties.memory,
      docker_image: docker_image,
      run_as_user: run_as_user,
      run_command: run_command,
      variables: variables_installation_params,
      services: services_installation_params,
      eports: eports_installation_params
    }
  end

  def variables_installation_params
    {}.tap do |result|
      application.variables.each do |variable|
        result[variable.name.to_sym] = variable.value
      end
    end
  end
  
  def services_installation_params
    application.application_service_connectors.map do |service|
      {}.tap do |result|
        type = service.application_service_connector_configuration.create_type.to_sym
        result[:create_type] = service.application_service_connector_configuration.create_type.to_s
        result[:publisher_namespace] = service.publisher_namespace
        result[:type_path] = service.type_path
        result[:variables] = service.application_service_connector_configuration.variable_values_params
        result[:existing_service] = service.application_service_connector_configuration.existing_service_params
      end
    end
  end

  def eports_installation_params
    application.eports.map do |eport|
      {}.tap do |result|
        result[:name] = eport.name
        result[:internal_port] = eport.internal_port
        result[:external_port] = eport.external_port
        result[:tcp] = eport.protocol.include?('TCP')
        result[:udp] = eport.protocol.include?('UDP')
      end
    end
  end
  
  def install
    engines_api.build_engine_from_docker_image(@install_from_docker_hub.installation_params)
  end

  def available_services
    engines_api.load_avail_services_for_type 'ManagedEngine'
  end

  def docker_image_validation
    if docker_image.blank?
      errors.add(:docker_image, ["Docker image source", "is required"])
    end
  end
  
end

app/controllers/install_from_docker_hubs_controller.rb
class InstallFromDockerHubsController < ApplicationController

  def new
    @install_from_docker_hub = InstallFromDockerHub.build_new
  end
  
  def create
    @install_from_docker_hub = InstallFromDockerHub.new(install_from_docker_hub_params)
    if @install_from_docker_hub.ready_to_configure?
      redirect_to new_install_from_docker_hub_configuration_path(@install_from_docker_hub.new_configuration_params)
    else
      render :new
    end
  end
    
private

  def install_from_docker_hub_params
    @software_install_params ||= params.require(:install_from_docker_hub).permit!
  end

end

app/views/install_from_docker_hubs/_application_service_connector_type_fields.html.erb
<div class="col-sm-12">

	<div class="panel panel-default top-gap">

		<div class="panel-heading">

			<div class="pull-right clearfix">
				<%= link_to content_tag(:i, nil, class:"fa fa-trash"), "javascript:;", onclick: "javascript: remove_fields(this); ",
				class: "btn btn-default btn-noborder btn-lg pull-right",
				data: { confirm: "Confirm", confirmdetail: "Remove service?", holderclass: "application_service_fields" } %>
			</div>

			<%= application_service_connector.title %>
			<small>
				<br>
				<%= application_service_connector.description %>
				(<%= application_service_connector.publisher_namespace.to_s + ":" + application_service_connector.type_path.to_s%>)
				<br>
			</small>

		</div>

		<div class="panel-body">
			<% select_collection = [ [:new, "Create new application service"] ]
				if application_service_connector.connectable_active_connected_services.present?
				  select_collection << [:active, "Use existing active application service"]
				end
				if application_service_connector.connectable_orphan_connected_services.present?
				  select_collection << [:orphan, "Use existing orphaned application service"]
			    end
			%>
			<div class="application_service_select_create_type">
				<div class="col-sm-12">
					<%= render 'shared/form/radio_buttons', f: f, name: :create_type, label: false,
							select_collection: select_collection, value_method: :first, text_method: :last, value: :new,
							field_class: "application_service_select_create_type_radios" %>
				</div>
			</div>
			
			<% if application_service_connector.connectable_active_connected_services.present? %>

				<div class="application_service_active_configure">
					<div class="col-sm-12">
						<%= render 'shared/form/select', f: f, name: :active_service, label: "Active application service",
								select_collection: application_service_connector.connectable_active_connected_services,
								select_class: "application_service_active_configure_select" %>
					</div>
				</div>
				
			<% end %>

			<% if application_service_connector.connectable_orphan_connected_services.present? %>

				<div class="application_service_orphan_configure">
					<div class="col-sm-12">
						<%= render 'shared/form/select', f: f, name: :orphan_service, label: "Orphaned application service",
						select_collection: application_service_connector.connectable_orphan_connected_services,
								select_class: "application_service_orphan_configure_select" %> 
					</div>
				</div>

			<% end %>


		</div>
	</div>
</div>

app/views/install_from_docker_hubs/_application_service_connectors.html.erb
<%= render 'shared/form/legend', text: 'Services' %>
<%= f.fields_for :application_service_connectors do |ff| %>
    <div class="application_service_fields">
		<%= render 'shared/form/hidden_field', name: :_destroy, f: ff, input_class: :destroy_input %>
		<%= ff.hidden_field :type_path %>
		<%= ff.hidden_field :publisher_namespace %>
		<%= ff.fields_for :application_service_connector_type do |fff| %>
			<%= render 'application_service_connector_type_fields', f: fff, application_service_connector: ff.object %>
		<% end %>
	</div>
<% end %>
<%= render 'new_application_service_button' %>

app/views/install_from_docker_hubs/_application_service_fields.html.erb
<div class="col-sm-12 application_service_fields">

	<div class="panel panel-default top-gap">

		<div class="panel-heading">

			<div class="pull-right clearfix">
				<%= render 'shared/form/hidden_field', name: :_destroy, f: f %>
				<%= link_to (content_tag(:i, nil, class:"fa fa-trash") + " Remove"), "javascript:;", onclick: "javascript: remove_fields(this); ",
				class: "btn btn-default btn-noborder btn-lg pull-right",
				data: { confirm: "Confirm", confirmdetail: "Remove service?", holderclass: "application_service_fields" } %>
			</div>

			<%= f.object.title %>
			<small>
				<br>
				<%= f.object.description %>
				(<%= f.object.publisher_namespace.to_s + ":" + f.object.type_path.to_s%>)
				<br>
			</small>

		</div>

		<div class="panel-body">
			<% select_collection = [ [:new, "Create new application service"] ]
				if f.object.attachable_active_attached_services.present?
				  select_collection << [:active, "Use existing active application service"]
				end
				if f.object.attachable_orphaned_attached_services.present?
				  select_collection << [:orphan, "Use existing orphaned application service"]
			    end
			%>
			<div class="application_service_select_create_type">
				<div class="col-sm-12">
					<%= render 'shared/form/radio_buttons', f: f, name: :create_type, value: f.object.create_type, label: false,
							select_collection: select_collection, value_method: :first, text_method: :last, default_value: :new,
							field_class: "application_service_select_create_type_radios" %>
				</div>
			</div>

			<div class="new_application_service_configure col-sm-12">
			  <%= render partial: 'variables/form_fields', locals: {f: f} %>
			</div>
			
			<% if f.object.attachable_active_attached_services.present? %>

				<div class="application_service_active_configure">
					<div class="col-sm-12">
						<%= render 'shared/form/select', f: f, name: :active_service, label: "Active application service",
								select_collection: f.object.attachable_active_attached_services,
								select_class: "application_service_active_configure_select" %>
					</div>
				</div>
				
			<% end %>

			<% if f.object.attachable_orphaned_attached_services.present? %>

				<div class="application_service_orphan_configure">
					<div class="col-sm-12">
						<%= render 'shared/form/select', f: f, name: :orphan_service, label: "Orphaned application service",
						select_collection: f.object.attachable_orphaned_attached_services,
								select_class: "application_service_orphan_configure_select" %> 
					</div>
				</div>

			<% end %>

			<%= f.hidden_field :type_path %>
			<%= f.hidden_field :publisher_namespace %>

		</div>
	</div>
</div>

app/views/install_from_docker_hubs/_environment_variable_fields.html.erb
<div class="col-sm-12 environment_variable_fields">

	<div class="panel panel-default top-gap">

		<div class="panel-body">

				<%= render 'shared/form/text_field', f: f, name: :name %>
				<%= render 'shared/form/text_field', f: f, name: :value %>
				
				<div class="col-sm-12 clearfix">
					<%= render 'shared/form/hidden_field', name: :_destroy, f: f, input_class: :destroy_input %>
					<%= link_to content_tag(:i, nil, class:"fa fa-trash"), "javascript:;", onclick: "javascript: remove_fields(this); ",
					class: "btn btn-default btn-noborder btn-lg pull-right",
					data: { confirm: "Confirm", confirmdetail: "Remove environment variable?", holderclass: "environment_variable_fields" } %>
				</div>
			
		</div>
	</div>
</div>

app/views/install_from_docker_hubs/_environment_variables.html.erb
<%= render 'shared/form/legend', text: 'Environment variables' %>

<%= f.fields_for :variables do |ff| %>
	<%= render 'environment_variable_fields', f: ff %>
<% end %>

<%= render 'new_environment_variable_button', f: f %>

app/views/install_from_docker_hubs/_eport_fields.html.erb
<div class="col-sm-12 eport_fields">

	<div class="panel panel-default top-gap">

		<div class="panel-body">

				<%= render 'shared/form/text_field', f: f, name: :name %>
				<%= render 'shared/form/text_field', f: f, name: :internal_port %>
				<%= render 'shared/form/text_field', f: f, name: :external_port %>
				<%= render 'shared/form/radio_buttons', f: f, name: :protocol %>

				<div class="col-sm-12 clearfix">
					<%= render 'shared/form/hidden_field', name: :_destroy, f: f, input_class: :destroy_input %>
					<%= link_to content_tag(:i, nil, class:"fa fa-trash"), "javascript:;", onclick: "javascript: remove_fields(this); ",
					class: "btn btn-default btn-noborder btn-lg pull-right",
					data: { confirm: "Confirm", confirmdetail: "Remove external port?", holderclass: "eport_fields" } %>
				</div>
			
		</div>
	</div>
</div>

app/views/install_from_docker_hubs/_eports.html.erb
<%= render 'shared/form/legend', text: 'Mapped ports' %>
<%= f.fields_for :eports do |ff| %>
	<%= render 'eport_fields', f: ff %>
<% end %>
<%= render 'new_eport_button', f: f %>

app/views/install_from_docker_hubs/_new_application_service_button.html.erb
<div class="col-sm-12 clearfix">

	<% 	available_services = @install_from_docker_hub.available_services %>

	<div class="dropdown pull-right">

		<button class="btn btn-lg btn-default dropdown-toggle" id="docker_hub_install_new_application_services_button" type="button" data-toggle="dropdown">
			<%= content_tag(:i, "", class: "fa fa-arrows-v") + " Connect service" %>
			<span class="caret"></span>
		</button>
		<ul class="dropdown-menu" role="menu">

			<% available_services.each do |available_service|
				link_data = {typepath: available_service[:type_path], publishernamespace: available_service[:publisher_namespace]}
			%>
				<li>
					<% fa_handle = Engines::Services.titles_data[available_service[:service_container].to_sym][:fa_icon] %>
					<%= link_to(
					content_tag(:i, nil, class: 'fa fa-' + fa_handle.to_s) + ' ' + available_service[:title], 'javascript:;',
					data: link_data,
					class: "btn-lg trigger-response-modal docker_hub_install_new_attach_services_menu_button")
					%>
				</li>

			<% end %>

		</ul>
	</div>

</div>

app/views/install_from_docker_hubs/_new_environment_variable_button.html.erb
<div class="col-sm-12 clearfix">
	<%= link_to(
	content_tag(:i, nil, class: "fa fa-question-circle ") + " Add environment variable", 'javascript:;',
	class: "btn btn-default btn-lg pull-right trigger-response-modal", id: "docker_hub_install_new_environment_variable_button")
	%>
</div>

app/views/install_from_docker_hubs/_new_eport_button.html.erb
<div class="col-sm-12 clearfix">
	<%= link_to(
	content_tag(:i, nil, class: "fa fa-external-link-square") + " Add mapped port", 'javascript:;',
	class: "btn btn-default btn-lg pull-right trigger-response-modal", id: "docker_hub_install_new_eport_button")
	%>
</div>

app/views/install_from_docker_hubs/new.html.erb
<div class="col-md-12">
	<h2><%= image_tag('docker_icon.png', height: '30') %> Install from Docker image - step 1</h2>
</div>

	<%= form_for @install_from_docker_hub, url: install_from_docker_hub_path do |f| %>
		<%= render 'shared/form/errors', f: f, verb: :installed, label: 'Docker image' %>
		<%= f.hidden_field :scroll_form_to %>
		<%= f.hidden_field :new_application_service_publisher_namespace %>
		<%= f.hidden_field :new_application_service_type_path %>
		<%= f.hidden_field :new_environment_variable %>
		<%= f.hidden_field :new_eport %>
		<%= f.hidden_field :docker_image %>
		<%= f.hidden_field :run_as_user %>
		<%= f.hidden_field :run_command %>
		<%= render 'shared/form/legend', text: 'Docker image' %>
		<%= render 'shared/form/text_field', f: f, name: :docker_image, label: 'Source URL' %>		
		<%= f.fields_for :application do |ff| %>
			<%= render 'shared/form/legend', text: 'Engine' %>
			<%= render 'shared/form/text_field', f: ff, name: :container_name, label: 'Name' %>		
			<%= render 'application_service_connectors', f: ff %>
			<%= render 'environment_variables', f: ff %>
			<%= render 'eports', f: ff %>
		<% end %>
		<%= render 'shared/form/legend', html_class: "top-gap" %>
		<%= render 'shared/form/cancel_and_submit_buttons', f: f, cancel_path: installer_path, submit_fa: 'arrow-right', submit_label: 'Next' %>
	<% end %>