config/routes.rb
Rails.application.routes.draw do

  root to: "desktops#show"

#Navbar

  resource :navbar_system_status

#Users

  get 'sign_in', to: redirect('/users/sign_in')

  devise_for :users, skip: :registrations, :controllers => { :sessions => "user_sessions" }
  resource :user, only: :show
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  # resource :user_password

#Desktop

  resource :desktop
  resource :desktop_applications

#Control panel

  resource :control_panel do
    get :services
  end
  resource :control_panel_applications
  resource :control_panel_services
  resource :services_registry
  resource :control_panel_applications_states
  resource :control_panel_services_states

#System

  resource :system_monitor_charts do
    get :system_cpu_usage
    get :system_cpu_usage_averages
    get :total_system_memory_usage
    get :total_container_memory_usage
    get :container_memory_usage
    get :total_applications_memory_usage
    get :applications_memory_usage
    get :total_services_memory_usage
    get :services_memory_usage
    get :disk_usage
    get :network_usage
  end

  resource :system_monitor_charts

  resource :system do
    get :monitor, :status, :info, :logs, :base_system, :updater, :restart
  end
  resource :system_restart do
    get :progress
  end
  resource :system_engines_update do
    get :progress
  end
  resource :system_base_update do
    get :progress
  end
  resource :system_restart_mgmt do
    get :progress
  end
  resource :system_restart_registry do
    get :progress
  end

  resource :system_security
  resource :system_security_certificate do
    get :download
  end
  resource :system_security_key do
    get :new_download
    post :download
  end
  resource :system_bug_reports

#Domains

  resource :domains_manager
  resource :domain
  resource :domain_certificate
  resource :domain_default_name
  resource :domain_default_site

#Display settings

  resource :display_settings

#Libraries

  resources :libraries
  resource :library_software do
    get :tags_list
  end
  resource :library_settings

#Applications

  resource :application_network_properties
  resource :application_resources_properties
  resource :application_variables_properties
  resource :application_display_properties
  resource :application_services_properties
  resource :application_service do
    get :action
  end
  resource :application_service_connector_type
  resource :application_service_connector_configuration
  resource :application_action do
    get :perform
  end
  resource :application_report do
    get :installation_report
  end
  resource :application_about
  resource :orphaned_application_service
  resource :application_service_connection_subservice_connection
  resource :application_service_connection_subservice_connector_configuration
  resource :application_service_data_export
  resource :application_service_data_import
  resource :application_uninstall
  resource :applications do
    get(
      :start_container, :stop_container, :pause_container, :unpause_container, :restart_container,
      :create_container, :destroy_container, :recreate_container,
      :reinstall, :open_first_run, :reload)
  end

#Services

  resource :service_report
  resource :service_configuration
  resource :service_action do
    get :perform
  end
  resource :services do
    get(
      :pause_container, :unpause_container, :start_container, :stop_container,
      :restart_container, :recreate_container, :create_container, :reload) # :show,
  end

#Installer

  resource :installer
  resource :application_installation do
    get(:preparing_installation, :preparing_installation_progress, :installing,
     :progress, :cancel)
  end
  resource :install_from_blueprint
  resource :install_from_repository_url
  resource :install_from_docker_hub
  resource :install_from_docker_hub_configuration

#First run

  resource :first_run do
    get :cancel
  end

#Help

  resource :help

end

app/models/domain_certificate.rb
class DomainCertificate < ActiveRecord::Base

  # extend Engines::Api
# 
  # attr_accessor(
    # :country,
    # :state,
    # :city,
    # :organization_name,
    # :person_name,
    # :certificate)
# 
  # attr_accessor :delete_certificate_file
  # has_attached_file :certificate_file, dependent: :destroy
  # validates_attachment_content_type :certificate_file #, :content_type => /\Aimage\/.*\Z/
  # before_validation { certificate_file.clear if delete_certificate_file == '1' }
# 
  # validates :country,
            # :state,
            # :city,
            # :organization_name,
            # :person_name, presence: true
#     
  # def self.load domain_key
    # new(domain_key: domain_key)
  # end
# 
  # def self.load_all
    # engines_api.certificates
  # end
# 
  # def domain_name
    # @domain_name ||= Domain.key_to_domain_name domain_key
  # end
# 
  # def create domain_certificate_params
    # assign_attributes domain_certificate_params
    # valid? && create_certificate
  # end
#     
  # def create_certificate
    # self.class.engines_api.create_ssl_certificate(
      # domain_name: domain_name,
      # person_name: person_name,
      # organization_name: organization_name,
      # city: city,
      # state: state,
      # country: country).was_success
  # end

end

app/controllers/domain_certificates_controller.rb
class DomainCertificatesController < ApplicationController

  before_action :set_domain_certificate
  
  def show
  end
  
  def new
  end

  def create
    if @domain_certificate.create domain_certificate_params
      redirect_to domain_certificate_path(domain_name: domain_key), notice: "Successfully created a new certificate for #{domain_name}."
    else
      render :new
    end
  end

  private

  def set_domain_certificate
    @domain_certificate = DomainCertificate.load domain_key
  end

  def domain_key
    params[:domain_name]
  end
  
  def domain_name
    Domain.key_to_domain_name domain_key
  end

  def domain_certificate_params
    params.require(:domain_certificate).permit!
  end

end

app/views/domain_certificates/new.html.erb
<div class="col-sm-12 top-gap">
  <h3><i class="fa fa-certificate"></i> SSL certificate for <%= @domain_certificate.domain_name %></h3>

  <%= form_for @domain_certificate, url: domain_certificate_path(domain_name: @domain_certificate.domain_key) do |f| %>
    <%= render partial: 'shared/form/errors', locals: {f: f} %>
    <%= render partial: 'shared/form/text_field', locals: {name: :person_name, f: f} %>
    <%= render partial: 'shared/form/text_field', locals: {name: :organization_name, f: f} %>
    <%= render partial: 'shared/form/text_field', locals: {name: :city, f: f} %>
    <%= render partial: 'shared/form/text_field', locals: {name: :state, f: f} %>
    <%= render partial: 'shared/form/country_select', locals: {name: :country, f: f} %>
    <%= render partial: 'shared/form/cancel_and_submit_buttons', locals: {f: f, cancel_path: domains_manager_path} %>
  <% end %>
</div>

app/views/domain_certificates/show.html.erb
<div class='row'>

	<div class="col-sm-12">
		<h2><i class="fa fa-globe"></i> Domain certificate for <%= @domain_certificate.domain_name %></h2>
	</div>

	<div class="col-sm-12">

		<%= link_to content_tag(:i, "", class: "fa fa-arrow-left") + ' Back', domains_manager_path, class: "btn btn-warning btn-lg trigger-response-modal" %>
		<%= link_to content_tag(:i, "", class: "fa fa-pencil") + " Self-sign", new_domain_certificate_path(domain_name: @domain_certificate.domain_key), class: "btn btn-lg btn-default trigger-response-modal" %>
		<%= link_to content_tag(:i, "", class: "fa fa-paste") + " Paste", new_domain_certificate_path(domain_name: @domain_certificate.domain_key), class: "btn btn-lg btn-default trigger-response-modal" %>
		<%= link_to content_tag(:i, "", class: "fa fa-upload") + " Upload", new_domain_certificate_path(domain_name: @domain_certificate.domain_key), class: "btn btn-lg btn-default trigger-response-modal" %>

		<div class="well top-gap">
			certificate details
		</div>


	</div>

</div>